main = {'columns': {
    # 'logoid': {'label': 'Logo ID', 'format': None},
    'name': {'label': 'Name'},
    'description': {'label': 'Description'},
    'currency': {'label': 'Currency'},
    'fundamental_currency_code': {'label': 'Fundamental Currency Code'},
    'minmov': {'label': 'Min Move'},
    'minmove2': {'label': 'Min Move 2'},
    'pricescale': {'label': 'Price Scale'},
    'subtype': {'label': 'Subtype'},
    'type': {'label': 'Type'},
    'fractional': {'label': 'Fractional', 'format': 'bool'},
    'ADR': {'label': 'Average Day Range (14)', 'format': None, 'interval': True},
    'ADX': {'label': 'Average Directional Index (14)', 'format': None, 'interval': True},
    'ADX+DI': {'label': 'Positive Directional Indicator (14)', 'format': None, 'interval': True},
    'ADX-DI': {'label': 'Negative Directional Indicator (14)', 'format': None, 'interval': True},
    'AO': {'label': 'Awesome Oscillator', 'format': None, 'interval': True},
    'ATR': {'label': 'Average True Range (14)', 'format': None, 'interval': True},
    'Aroon.Down': {'label': 'Aroon Down (14)', 'format': None, 'interval': True},
    'Aroon.Up': {'label': 'Aroon Up (14)', 'format': None, 'interval': True},
    'BB.lower': {'label': 'Bollinger Lower Band (20)', 'format': None, 'interval': True},
    'BB.upper': {'label': 'Bollinger Upper Band (20)', 'format': None, 'interval': True},
    'BBPower': {'label': 'Bull Bear Power', 'format': None, 'interval': True},  # Unknown column name Rec.BBPower
    'CCI20': {'label': 'Commodity Channel Index (20)', 'format': None, 'interval': True},
    'DonchCh20.Lower': {'label': 'Donchian Channels Lower Band (20)',
                        'format': None, 'interval': True},
    'DonchCh20.Upper': {'label': 'Donchian Channels Upper Band (20)',
                        'format': None, 'interval': True},
    'EMA10': {'label': 'Exponential Moving Average (10)', 'format': None, 'interval': True},
    'EMA100': {'label': 'Exponential Moving Average (100)', 'format': None, 'interval': True},
    'EMA20': {'label': 'Exponential Moving Average (20)', 'format': None, 'interval': True},
    'EMA200': {'label': 'Exponential Moving Average (200)', 'format': None, 'interval': True},
    'EMA30': {'label': 'Exponential Moving Average (30)', 'format': None, 'interval': True},
    'EMA5': {'label': 'Exponential Moving Average (5)', 'format': None, 'interval': True},
    'EMA50': {'label': 'Exponential Moving Average (50)', 'format': None, 'interval': True},
    'High.1M': {'label': '1-Month High', 'format': None},
    'High.3M': {'label': '3-Month High', 'format': None},
    'High.6M': {'label': '6-Month High', 'format': None},
    'High.All': {'label': 'All Time High', 'format': None},
    'HullMA9': {'label': 'Hull Moving Average (9)', 'format': None, 'interval': True},  # Unknown column name Rec.HullMA9
    'Ichimoku.BLine': {'label': 'Ichimoku Base Line (9, 26, 52, 26)',
                       'format': None, 'interval': True}, # Unknown column name Rec.Ichimoku|1W
    'Ichimoku.CLine': {'label': 'Ichimoku Conversion Line (9, 26, 52, 26)',
                       'format': None, 'interval': True},
    'Ichimoku.Lead1': {'label': 'Ichimoku Leading Span A (9, 26, 52, 26)',
                       'format': None, 'interval': True},
    'Ichimoku.Lead2': {'label': 'Ichimoku Leading Span B (9, 26, 52, 26)',
                       'format': None, 'interval': True},
    'KltChnl.lower': {'label': 'Keltner Channels Lower Band (20)',
                      'format': None, 'interval': True},
    'KltChnl.upper': {'label': 'Keltner Channels Upper Band (20)',
                      'format': None, 'interval': True},
    'Low.1M': {'label': '1-Month Low', 'format': None},
    'Low.3M': {'label': '3-Month Low', 'format': None},
    'Low.6M': {'label': '6-Month Low', 'format': None},
    'Low.All': {'label': 'All Time Low', 'format': None},
    'MACD.macd': {'label': 'MACD Level (12, 26)', 'format': None, 'interval': True},
    'MACD.signal': {'label': 'MACD Signal (12, 26)', 'format': None, 'interval': True},
    'Mom': {'label': 'Momentum (10)', 'format': None, 'interval': True},
    'P.SAR': {'label': 'Parabolic SAR', 'format': None, 'interval': True},
    'Perf.1M': {'label': 'Monthly Performance', 'format': 'percent'},
    'Perf.3M': {'label': '3-Month Performance', 'format': 'percent'},
    'Perf.5Y': {'label': '5Y Performance', 'format': 'percent'},
    'Perf.6M': {'label': '6-Month Performance', 'format': 'percent'},
    'Perf.All': {'label': 'All Time Performance', 'format': 'percent'},
    'Perf.W': {'label': 'Weekly Performance', 'format': 'percent'},
    'Perf.Y': {'label': 'Yearly Performance', 'format': 'percent'},
    'Perf.YTD': {'label': 'YTD Performance', 'format': 'percent'},
    'Pivot.M.Camarilla.Middle': {'label': 'Pivot Camarilla P', 'format': None, 'interval': True},
    'Pivot.M.Camarilla.R1': {'label': 'Pivot Camarilla R1', 'format': None, 'interval': True},
    'Pivot.M.Camarilla.R2': {'label': 'Pivot Camarilla R2', 'format': None, 'interval': True},
    'Pivot.M.Camarilla.R3': {'label': 'Pivot Camarilla R3', 'format': None, 'interval': True},
    'Pivot.M.Camarilla.S1': {'label': 'Pivot Camarilla S1', 'format': None, 'interval': True},
    'Pivot.M.Camarilla.S2': {'label': 'Pivot Camarilla S2', 'format': None, 'interval': True},
    'Pivot.M.Camarilla.S3': {'label': 'Pivot Camarilla S3', 'format': None, 'interval': True},
    'Pivot.M.Classic.Middle': {'label': 'Pivot Classic P', 'format': None, 'interval': True},
    'Pivot.M.Classic.R1': {'label': 'Pivot Classic R1', 'format': None, 'interval': True},
    'Pivot.M.Classic.R2': {'label': 'Pivot Classic R2', 'format': None, 'interval': True},
    'Pivot.M.Classic.R3': {'label': 'Pivot Classic R3', 'format': None, 'interval': True},
    'Pivot.M.Classic.S1': {'label': 'Pivot Classic S1', 'format': None, 'interval': True},
    'Pivot.M.Classic.S2': {'label': 'Pivot Classic S2', 'format': None, 'interval': True},
    'Pivot.M.Classic.S3': {'label': 'Pivot Classic S3', 'format': None, 'interval': True},
    'Pivot.M.Demark.Middle': {'label': 'Pivot DM P', 'format': None, 'interval': True},
    'Pivot.M.Demark.R1': {'label': 'Pivot DM R1', 'format': None, 'interval': True},
    'Pivot.M.Demark.S1': {'label': 'Pivot DM S1', 'format': None, 'interval': True},
    'Pivot.M.Fibonacci.Middle': {'label': 'Pivot Fibonacci P', 'format': None, 'interval': True},
    'Pivot.M.Fibonacci.R1': {'label': 'Pivot Fibonacci R1', 'format': None, 'interval': True},
    'Pivot.M.Fibonacci.R2': {'label': 'Pivot Fibonacci R2', 'format': None, 'interval': True},
    'Pivot.M.Fibonacci.R3': {'label': 'Pivot Fibonacci R3', 'format': None, 'interval': True},
    'Pivot.M.Fibonacci.S1': {'label': 'Pivot Fibonacci S1', 'format': None, 'interval': True},
    'Pivot.M.Fibonacci.S2': {'label': 'Pivot Fibonacci S2', 'format': None, 'interval': True},
    'Pivot.M.Fibonacci.S3': {'label': 'Pivot Fibonacci S3', 'format': None, 'interval': True},
    'Pivot.M.Woodie.Middle': {'label': 'Pivot Woodie P', 'format': None, 'interval': True},
    'Pivot.M.Woodie.R1': {'label': 'Pivot Woodie R1', 'format': None, 'interval': True},
    'Pivot.M.Woodie.R2': {'label': 'Pivot Woodie R2', 'format': None, 'interval': True},
    'Pivot.M.Woodie.R3': {'label': 'Pivot Woodie R3', 'format': None, 'interval': True},
    'Pivot.M.Woodie.S1': {'label': 'Pivot Woodie S1', 'format': None, 'interval': True},
    'Pivot.M.Woodie.S2': {'label': 'Pivot Woodie S2', 'format': None, 'interval': True},
    'Pivot.M.Woodie.S3': {'label': 'Pivot Woodie S3', 'format': None, 'interval': True},
    'ROC': {'label': 'Rate Of Change (9)', 'format': None, 'interval': True},
    'RSI': {'label': 'Relative Strength Index (14)', 'format': None, 'interval': True},
    'RSI7': {'label': 'Relative Strength Index (7)', 'format': None, 'interval': True},
    'Recommend.All': {'label': 'Technical Rating', 'format': 'rating', 'interval': True},
    'Recommend.MA': {'label': 'Moving Averages Rating', 'format': 'rating', 'interval': True},
    'Recommend.Other': {'label': 'Oscillators Rating', 'format': 'rating', 'interval': True},
    'SMA10': {'label': 'Simple Moving Average (10)', 'format': None, 'interval': True},
    'SMA100': {'label': 'Simple Moving Average (100)', 'format': None, 'interval': True},
    'SMA20': {'label': 'Simple Moving Average (20)', 'format': None, 'interval': True},
    'SMA200': {'label': 'Simple Moving Average (200)', 'format': None, 'interval': True},
    'SMA30': {'label': 'Simple Moving Average (30)', 'format': None, 'interval': True},
    'SMA5': {'label': 'Simple Moving Average (5)', 'format': None, 'interval': True},
    'SMA50': {'label': 'Simple Moving Average (50)', 'format': None, 'interval': True},
    'Stoch.D': {'label': 'Stochastic %D (14, 3, 3)', 'format': None, 'interval': True},
    'Stoch.K': {'label': 'Stochastic %K (14, 3, 3)', 'format': None, 'interval': True},
    'Stoch.RSI.D': {'label': 'Stochastic RSI Slow (3, 3, 14, 14)',
                    'format': None, 'interval': True},
    'Stoch.RSI.K': {'label': 'Stochastic RSI Fast (3, 3, 14, 14)',
                    'format': None, 'interval': True},
    'UO': {'label': 'Ultimate Oscillator (7, 14, 28)', 'format': None, 'interval': True},
    'VWAP': {'label': 'Volume Weighted Average Price', 'format': None, 'interval': True},
    'VWMA': {'label': 'Volume Weighted Moving Average (20)', 'format': None, 'interval': True},
    'Volatility.D': {'label': 'Volatility', 'format': None},
    'Volatility.M': {'label': 'Volatility Month', 'format': None},
    'Volatility.W': {'label': 'Volatility Week', 'format': None},
    'W.R': {'label': 'Williams Percent Range (14)', 'format': None, 'interval': True},  # Rec.WR
    'change': {'label': 'Change %', 'format': None, 'interval': True},
    'close': {'label': 'Price', 'format': None, 'interval': True},
    'gap': {'label': 'Gap %', 'format': None, 'interval': True},
    'high': {'label': 'High', 'format': None, 'interval': True},
    'low': {'label': 'Low', 'format': None, 'interval': True},
    'open': {'label': 'Open', 'format': None, 'interval': True},
    'price_52_week_high': {'label': '52 Week High', 'format': None},
    'price_52_week_low': {'label': '52 Week Low', 'format': None},
}
}

stock = {
    'markets': [
        'america',
        'uk',
        'india',
        'spain',
        'russia',
        'australia',
        'brazil',
        'japan',
        'newzealand',
        'turkey',
        'switzerland',
        'hongkong',
        'taiwan',
        'netherlands',
        'belgium',
        'portugal',
        'france',
        'mexico',
        'canada',
        'colombia',
        'uae',
        'nigeria',
        'singapore',
        'germany',
        'pakistan',
        'peru',
        'poland',
        'italy',
        'argentina',
        'israel',
        'egypt',
        'srilanka',
        'serbia',
        'chile',
        'china',
        'malaysia',
        'morocco',
        'ksa',
        'bahrain',
        'qatar',
        'indonesia',
        'finland',
        'iceland',
        'denmark',
        'romania',
        'hungary',
        'sweden',
        'slovakia',
        'lithuania',
        'luxembourg',
        'estonia',
        'latvia',
        'vietnam',
        'rsa',
        'thailand',
        'tunisia',
        'korea',
        'kenya',
        'kuwait',
        'norway',
        'philippines',
        'greece',
        'venezuela',
        'cyprus',
        'bangladesh',
    ],
    'columns': {'ChaikinMoneyFlow': {'label': 'Chaikin Money Flow (20)', 'format': None},
                'MoneyFlow': {'label': 'Money Flow (14)', 'format': None, 'interval': True},
                'Value.Traded': {'label': 'Volume*Price', 'format': None, 'interval': True},
                'after_tax_margin': {'label': 'Net Margin (TTM)', 'format': None},
                'basic_eps_net_income': {'label': 'Basic EPS (FY)', 'format': None},
                'beta_1_year': {'label': '1-Year Beta', 'format': None},
                'cash_n_equivalents_fq': {'label': 'Cash & Equivalents (MRQ)',
                                          'format': None},
                'cash_n_equivalents_fy': {'label': 'Cash & Equivalents (FY)', 'format': None},
                'cash_n_short_term_invest_fq': {'label': 'Cash and short term investments (MRQ)',
                                                'format': None},
                'cash_n_short_term_invest_fy': {'label': 'Cash and short term investments (FY)',
                                                'format': None},
                'current_ratio': {'label': 'Current Ratio (MRQ)', 'format': None},
                'debt_to_equity': {'label': 'Debt to Equity Ratio (MRQ)', 'format': None},
                'dividend_yield_recent': {'label': 'Dividend Yield Forward', 'format': None},
                'dividends_paid': {'label': 'Dividends Paid (FY)', 'format': None},
                'dividends_per_share_fq': {'label': 'Dividends per Share (MRQ)',
                                           'format': None},
                'dps_common_stock_prim_issue_fy': {'label': 'Dividends per Share (FY)',
                                                   'format': None},
                'dps_common_stock_prim_issue_yoy_growth_fy': {'label': 'Dividends per share (Annual YoY Growth)',
                                                              'format': None},
                'earnings_per_share_basic_ttm': {'label': 'Basic EPS (TTM)', 'format': None},
                'earnings_per_share_diluted_qoq_growth_fq': {'label': 'EPS Diluted (Quarterly QoQ Growth)',
                                                             'format': None},
                'earnings_per_share_diluted_ttm': {'label': 'EPS Diluted (TTM)',
                                                   'format': None},
                'earnings_per_share_diluted_yoy_growth_fq': {'label': 'EPS Diluted (Quarterly YoY Growth)',
                                                             'format': None},
                'earnings_per_share_diluted_yoy_growth_fy': {'label': 'EPS Diluted (Annual YoY Growth)',
                                                             'format': None},
                'earnings_per_share_diluted_yoy_growth_ttm': {'label': 'EPS Diluted (TTM YoY Growth)',
                                                              'format': None},
                'earnings_per_share_forecast_next_fq': {'label': 'EPS Forecast (MRQ)',
                                                        'format': None},
                'earnings_per_share_fq': {'label': 'EPS Diluted (MRQ)', 'format': None},
                'earnings_release_date': {'label': 'Recent Earnings Date', 'format': None},
                'earnings_release_next_date': {'label': 'Upcoming Earnings Date',
                                               'format': None},
                'ebitda': {'label': 'EBITDA (TTM)', 'format': None},
                'ebitda_qoq_growth_fq': {'label': 'EBITDA (Quarterly QoQ Growth)',
                                         'format': None},
                'ebitda_yoy_growth_fq': {'label': 'EBITDA (Quarterly YoY Growth)',
                                         'format': None},
                'ebitda_yoy_growth_fy': {'label': 'EBITDA (Annual YoY Growth)',
                                         'format': None},
                'ebitda_yoy_growth_ttm': {'label': 'EBITDA (TTM YoY Growth)', 'format': None},
                'enterprise_value_ebitda_ttm': {'label': 'Enterprise Value/EBITDA (TTM)',
                                                'format': None},
                'enterprise_value_fq': {'label': 'Enterprise Value (MRQ)', 'format': None},
                'float_shares_outstanding': {'label': 'Shares Float', 'format': None},
                'free_cash_flow_margin_fy': {'label': 'Free Cash Flow Margin (FY)',
                                             'format': None},
                'free_cash_flow_margin_ttm': {'label': 'Free Cash Flow Margin (TTM)',
                                              'format': None},
                'free_cash_flow_qoq_growth_fq': {'label': 'Free Cash Flow (Quarterly QoQ Growth)',
                                                 'format': None},
                'free_cash_flow_yoy_growth_fq': {'label': 'Free Cash Flow (Quarterly YoY Growth)',
                                                 'format': None},
                'free_cash_flow_yoy_growth_fy': {'label': 'Free Cash Flow (Annual YoY Growth)',
                                                 'format': None},
                'free_cash_flow_yoy_growth_ttm': {'label': 'Free Cash Flow (TTM YoY Growth)',
                                                  'format': None},
                'goodwill': {'label': 'Goodwill', 'format': None},
                'gross_margin': {'label': 'Gross Margin (TTM)', 'format': None},
                'gross_profit': {'label': 'Gross Profit (FY)', 'format': None},
                'gross_profit_fq': {'label': 'Gross Profit (MRQ)', 'format': None},
                'gross_profit_margin_fy': {'label': 'Gross Margin (FY)', 'format': None},
                'gross_profit_qoq_growth_fq': {'label': 'Gross Profit (Quarterly QoQ Growth)',
                                               'format': None},
                'gross_profit_yoy_growth_fq': {'label': 'Gross Profit (Quarterly YoY Growth)',
                                               'format': None},
                'gross_profit_yoy_growth_fy': {'label': 'Gross Profit (Annual YoY Growth)',
                                               'format': None},
                'gross_profit_yoy_growth_ttm': {'label': 'Gross Profit (TTM YoY Growth)',
                                                'format': None},
                'industry': {'label': 'Industry', 'format': None},
                'last_annual_eps': {'label': 'EPS Diluted (FY)', 'format': None},
                'last_annual_revenue': {'label': 'Last Year Revenue (FY)', 'format': None},
                'market_cap_basic': {'label': 'Market Capitalization', 'format': None},
                'net_debt': {'label': 'Net Debt (MRQ)', 'format': None},
                'net_income': {'label': 'Net Income (FY)', 'format': None},
                'net_income_bef_disc_oper_margin_fy': {'label': 'Net Margin (FY)',
                                                       'format': None},
                'net_income_qoq_growth_fq': {'label': 'Net Income (Quarterly QoQ Growth)',
                                             'format': None},
                'net_income_yoy_growth_fq': {'label': 'Net Income (Quarterly YoY Growth)',
                                             'format': None},
                'net_income_yoy_growth_fy': {'label': 'Net Income (Annual YoY Growth)',
                                             'format': None},
                'net_income_yoy_growth_ttm': {'label': 'Net Income (TTM YoY Growth)',
                                              'format': None},
                'number_of_employees': {'label': 'Number of Employees', 'format': None},
                'number_of_shareholders': {'label': 'Number of Shareholders', 'format': None},
                'oper_income_margin_fy': {'label': 'Operating Margin (FY)', 'format': None},
                'operating_margin': {'label': 'Operating Margin (TTM)', 'format': None},
                'postmarket_change': {'label': 'Post-market Change %', 'format': None},
                'postmarket_change_abs': {'label': 'Post-market Change', 'format': None},
                'postmarket_close': {'label': 'Post-market Close', 'format': None},
                'postmarket_high': {'label': 'Post-market High', 'format': None},
                'postmarket_low': {'label': 'Post-market Low', 'format': None},
                'postmarket_open': {'label': 'Post-market Open', 'format': None},
                'postmarket_volume': {'label': 'Post-market Volume', 'format': None},
                'pre_tax_margin': {'label': 'Pretax Margin (TTM)', 'format': None},
                'premarket_change': {'label': 'Pre-market Change %', 'format': None},
                'premarket_change_abs': {'label': 'Pre-market Change', 'format': None},
                'premarket_change_from_open': {'label': 'Pre-market Change from Open %',
                                               'format': None},
                'premarket_change_from_open_abs': {'label': 'Pre-market Change from Open',
                                                   'format': None},
                'premarket_close': {'label': 'Pre-market Close', 'format': None},
                'premarket_gap': {'label': 'Pre-market Gap %', 'format': None},
                'premarket_high': {'label': 'Pre-market High', 'format': None},
                'premarket_low': {'label': 'Pre-market Low', 'format': None},
                'premarket_open': {'label': 'Pre-market Open', 'format': None},
                'premarket_volume': {'label': 'Pre-market Volume', 'format': None},
                'price_book_fq': {'label': 'Price to Book (MRQ)', 'format': None},
                'price_book_ratio': {'label': 'Price to Book (FY)', 'format': None},
                'price_earnings_ttm': {'label': 'Price to Earnings Ratio (TTM)',
                                       'format': None},
                'price_free_cash_flow_ttm': {'label': 'Price to Free Cash Flow (TTM)',
                                             'format': None},
                'price_revenue_ttm': {'label': 'Price to Revenue Ratio (TTM)',
                                      'format': None},
                'price_sales_ratio': {'label': 'Price to Sales (FY)', 'format': None},
                'quick_ratio': {'label': 'Quick Ratio (MRQ)', 'format': None},
                'relative_volume_10d_calc': {'label': 'Relative Volume', 'format': None, 'interval': True},
                'research_and_dev_ratio_fy': {'label': 'Research & development Ratio (FY)',
                                              'format': None},
                'research_and_dev_ratio_ttm': {'label': 'Research & development Ratio (TTM)',
                                               'format': None},
                'return_on_assets': {'label': 'Return on Assets (TTM)', 'format': None},
                'return_on_equity': {'label': 'Return on Equity (TTM)', 'format': None},
                'return_on_invested_capital': {'label': 'Return on Invested Capital (TTM)',
                                               'format': None},
                'revenue_per_employee': {'label': 'Revenue per Employee (FY)',
                                         'format': None},
                'sell_gen_admin_exp_other_ratio_fy': {'label': 'Selling General & Admin expenses Ratio (FY)',
                                                      'format': None},
                'sell_gen_admin_exp_other_ratio_ttm': {'label': 'Selling General & Admin expenses Ratio (TTM)',
                                                       'format': None},
                'submarket': {'label': 'Submarket', 'format': None},
                'total_assets': {'label': 'Total Assets (MRQ)', 'format': None},
                'total_assets_qoq_growth_fq': {'label': 'Total Assets (Quarterly QoQ Growth)',
                                               'format': None},
                'total_assets_yoy_growth_fq': {'label': 'Total Assets (Quarterly YoY Growth)',
                                               'format': None},
                'total_assets_yoy_growth_fy': {'label': 'Total Assets (Annual YoY Growth)',
                                               'format': None},
                'total_current_assets': {'label': 'Total Current Assets (MRQ)',
                                         'format': None},
                'total_debt': {'label': 'Total Debt (MRQ)', 'format': None},
                'total_debt_qoq_growth_fq': {'label': 'Total Debt (Quarterly QoQ Growth)',
                                             'format': None},
                'total_debt_yoy_growth_fq': {'label': 'Total Debt (Quarterly YoY Growth)',
                                             'format': None},
                'total_debt_yoy_growth_fy': {'label': 'Total Debt (Annual YoY Growth)',
                                             'format': None},
                'total_liabilities_fq': {'label': 'Total Liabilities (MRQ)', 'format': None},
                'total_liabilities_fy': {'label': 'Total Liabilities (FY)', 'format': None},
                'total_revenue': {'label': 'Total Revenue (FY)', 'format': None},
                'total_revenue_qoq_growth_fq': {'label': 'Revenue (Quarterly QoQ Growth)',
                                                'format': None},
                'total_revenue_yoy_growth_fq': {'label': 'Revenue (Quarterly YoY Growth)',
                                                'format': None},
                'total_revenue_yoy_growth_fy': {'label': 'Revenue (Annual YoY Growth)',
                                                'format': None},
                'total_revenue_yoy_growth_ttm': {'label': 'Revenue (TTM YoY Growth)',
                                                 'format': None},
                'total_shares_outstanding_fundamental': {'label': 'Total Shares Outstanding',
                                                         'format': None},
                'candlestick': {'label': 'Pattern', 'format': None, 'interval': True},
                'Candle.AbandonedBaby.Bearish': {'label': 'AbandonedBaby Bearish', 'format': None, 'interval': True},
                'Candle.AbandonedBaby.Bullish': {'label': 'AbandonedBaby Bullish', 'format': None, 'interval': True},
                'Candle.Engulfing.Bearish': {'label': 'Engulfing Bearish', 'format': None, 'interval': True},
                'Candle.Harami.Bearish': {'label': 'Harami Bearish', 'format': None, 'interval': True},
                'Candle.Engulfing.Bullish': {'label': 'Engulfing Bullish', 'format': None, 'interval': True},
                'Candle.Harami.Bullish': {'label': 'Harami Bullish', 'format': None, 'interval': True},
                'Candle.Doji': {'label': 'Doji', 'format': None, 'interval': True},
                'Candle.Doji.Dragonfly': {'label': 'Doji Dragonfly', 'format': None, 'interval': True},
                'Candle.EveningStar': {'label': 'EveningStar', 'format': None, 'interval': True},
                'Candle.Doji.Gravestone': {'label': 'Doji Gravestone', 'format': None, 'interval': True},
                'Candle.Hammer': {'label': 'Hammer', 'format': None, 'interval': True},
                'Candle.HangingMan': {'label': 'HangingMan', 'format': None, 'interval': True},
                'Candle.InvertedHammer': {'label': 'InvertedHammer', 'format': None, 'interval': True},
                'Candle.Kicking.Bearish': {'label': 'Kicking Bearish', 'format': None, 'interval': True},
                'Candle.Kicking.Bullish': {'label': 'Kicking Bullish', 'format': None, 'interval': True},
                'Candle.LongShadow.Lower': {'label': 'LongShadow Lower', 'format': None, 'interval': True},
                'Candle.LongShadow.Upper': {'label': 'LongShadow Upper', 'format': None, 'interval': True},
                'Candle.Marubozu.Black': {'label': 'Marubozu Black', 'format': None, 'interval': True},
                'Candle.Marubozu.White': {'label': 'Marubozu White', 'format': None, 'interval': True},
                'Candle.MorningStar': {'label': 'MorningStar', 'format': None, 'interval': True},
                'Candle.ShootingStar': {'label': 'ShootingStar', 'format': None, 'interval': True},
                'Candle.SpinningTop.Black': {'label': 'SpinningTop Black', 'format': None, 'interval': True},
                'Candle.SpinningTop.White': {'label': 'SpinningTop White', 'format': None, 'interval': True},
                'Candle.3BlackCrows': {'label': '3BlackCrows', 'format': None, 'interval': True},
                'Candle.3WhiteSoldiers': {'label': '3WhiteSoldiers', 'format': None, 'interval': True},
                'Candle.TriStar.Bearish': {'label': 'TriStar Bearish', 'format': None, 'interval': True},
                'Candle.TriStar.Bullish': {'label': 'TriStar Bullish', 'format': None, 'interval': True},
                'change|1': {'label': 'Change 1m, %', 'format': None},
                'change|15': {'label': 'Change 15m, %', 'format': None},
                'change|1M': {'label': 'Change 1M, %', 'format': None},
                'change|1W': {'label': 'Change 1W, %', 'format': None},
                'change|240': {'label': 'Change 4h, %', 'format': None},
                'change|5': {'label': 'Change 5m, %', 'format': None},
                'change|60': {'label': 'Change 1h, %', 'format': None},
                'change_abs': {'label': 'Change', 'format': None, 'interval': True},
                'change_abs|1': {'label': 'Change 1m', 'format': None},
                'change_abs|15': {'label': 'Change 15m', 'format': None},
                'change_abs|1M': {'label': 'Change 1M', 'format': None},
                'change_abs|1W': {'label': 'Change 1W', 'format': None},
                'change_abs|240': {'label': 'Change 4h', 'format': None},
                'change_abs|5': {'label': 'Change 5m', 'format': None},
                'change_abs|60': {'label': 'Change 1h', 'format': None},
                'change_from_open': {'label': 'Change from Open %', 'format': None, 'interval': True},
                'change_from_open_abs': {'label': 'Change from Open', 'format': None, 'interval': True},

                'volume': {'label': 'Volume', 'format': None, 'interval': True}
                },
}
crypto = {
    'columns': {'24h_vol_change|5': {'label': 'Volume 24h Change %', 'format': None},
                '24h_vol|5': {'label': 'Volume 24h in USD', 'format': None},
                'ask': {'label': 'Ask', 'format': None},
                'average_volume_10d_calc': {'label': 'Average Volume (10 day)',
                                            'format': None},
                'average_volume_30d_calc': {'label': 'Average Volume (30 day)',
                                            'format': None},
                'average_volume_60d_calc': {'label': 'Average Volume (60 day)',
                                            'format': None},
                'average_volume_90d_calc': {'label': 'Average Volume (90 day)',
                                            'format': None},
                'bid': {'label': 'Bid', 'format': None},
                'exchange': {'label': 'Exchange', 'format': None},
                'market_cap_calc': {'label': 'Market Capitalization', 'format': None},
                'market_cap_diluted_calc': {'label': 'Fully Diluted Market Cap',
                                            'format': None},
                'relative_volume_10d_calc': {'label': 'Relative Volume', 'format': None, 'interval': True},
                'relative_volume_intraday|5': {'label': 'Relative Volume at Time',
                                               'format': None},
                'total_shares_diluted': {'label': 'Total Coins', 'format': None},
                'total_shares_outstanding': {'label': 'Available Coins', 'format': None},
                'total_value_traded': {'label': 'Traded Volume', 'format': None},
                'volume': {'label': 'Volume', 'format': None, 'interval': True}}}

forex = {
    'columns': {'ask': {'label': 'Ask', 'format': None},
                'bid': {'label': 'Bid', 'format': None},
                'country': {'label': 'Region', 'format': None},
                'sector': {'label': 'Group', 'format': None}},
}
